#import <HSWidgets/HSWidgetCombinedAdditionalOptionsAndPreferencesViewController.h>

@interface HSCustomWidgetPreferencesViewController : HSWidgetCombinedAdditionalOptionsAndPreferencesViewController
@end
