include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = HSSpacerWidget
HSSpacerWidget_FILES = HSSpacerWidgetViewController.mm
HSSpacerWidget_FRAMEWORKS = UIKit
HSSpacerWidget_EXTRA_FRAMEWORKS = HSWidgets
HSSpacerWidget_INSTALL_PATH = /Library/HSWidgets

include $(THEOS_MAKE_PATH)/bundle.mk
