#import "HSWidgets-structs.h"
#import "HSWidgetPositionObject.h"
#import "HSWidgetAvailablePositionObject.h"
#import "HSWidgetSizeObject.h"
#import "HSWidgetFrameObject.h"
#import "HSWidgetGridPositionConverterCache.h"
