#import <HSWidgets/HSWidgets-core.h>
#import <HSWidgets/HSWidgetAdditionalOptions.h>
#import <HSWidgets/HSWidgetAdditionalOptionsViewController.h>
#import <HSWidgets/HSWidgetAddNewAdditionalOptionsDelegate.h>
#import <HSWidgets/HSWidgetCombinedAdditionalOptionsAndPreferencesViewController.h>
#import <HSWidgets/HSWidgetDelegate.h>
#import <HSWidgets/HSWidgetPreferences.h>
#import <HSWidgets/HSWidgetPreferencesListController.h>
#import <HSWidgets/HSWidgetResources.h>
#import <HSWidgets/HSWidgetUnclippedView.h>
#import <HSWidgets/HSWidgetViewController.h>
#import <HSWidgets/HSModernWidgetViewController.h>
